### ISSUE TITLE
'python manage.py makemigrations' error

### ISSUE THREAD

**Issue by gustavklopp** [dreaswar/AuShadha#36]
Here's the error from the command `python manage.py makemigrations` :

```
Trying to run custom code at startup...
Loading apps and roles from configure.yaml
starting up
Traceback (most recent call last):
  File "manage.py", line 18, in <module>
    startup.run()
  File "/home/guido/BACKUP_guido/Documents/AuShadha/src/AuShadha/AuShadha/startup.py", line 77, in run
    autoload()
  File "/home/guido/BACKUP_guido/Documents/AuShadha/src/AuShadha/AuShadha/startup.py", line 73, in autoload
    load_modules()
  File "/home/guido/BACKUP_guido/Documents/AuShadha/src/AuShadha/AuShadha/startup.py", line 37, in load_modules
    import_module("{}.aushadha".format( app ) )
  File "/home/guido/.Envs/aushadha/local/lib/python2.7/site-packages/django/utils/importlib.py", line 45, in import_module
    __import__(name)
  File "/home/guido/BACKUP_guido/Documents/AuShadha/src/AuShadha/registry/icd10/aushadha.py", line 12, in <module>
    from .models import Chapter, Section,Diagnosis 
  File "/home/guido/BACKUP_guido/Documents/AuShadha/src/AuShadha/registry/icd10/models.py", line 14, in <module>
    from AuShadha.apps.aushadha_base_models.models import AuShadhaBaseModel
  File "/home/guido/BACKUP_guido/Documents/AuShadha/src/AuShadha/AuShadha/apps/aushadha_base_models/models.py", line 249, in <module>
    class AuShadhaBaseModelForm(ModelForm):
  File "/home/guido/.Envs/aushadha/local/lib/python2.7/site-packages/django/forms/models.py", line 274, in __new__
    "needs updating." % name
django.core.exceptions.ImproperlyConfigured: Creating a ModelForm without either the 'fields' attribute or the 'exclude' attribute is prohibited; form AuShadhaBaseModelForm needs updating.
```

**Comment by Kanr** [comment]
I am trying to build the app and running into this error. Any resolution?

**Comment by dreaswar** [comment]
@Kanr Thats an issue with the latest Django. Try with Django 1.8 or Django 1.7x. Please let me know if you still run into the error. The latest Django requires us to explicitly set a fields attribute on the ModelForm Class.

**Comment by Kanr** [comment]
@dreaswar Thank you for the quick reply, unfortunately I was to busy to resume my experiment until now. I tried downgrading django and am still having trouble Aushadha running. here is my most recent error output:
_______________________________________________
(aushadha)[admin@localhost AuShadha]$ python manage.py runserver
Trying to run custom code at startup...
Loading apps and roles from configure.yaml
Traceback (most recent call last):
  File "manage.py", line 17, in <module>
    import AuShadha.startup as startup
  File "/home/admin/virtualenv/aushadha/src/AuShadha/AuShadha/startup.py", line 19, in <module>
    from AuShadha import settings
  File "/home/admin/virtualenv/aushadha/src/AuShadha/AuShadha/settings.py", line 5, in <module>
    import yaml
ImportError: No module named yaml
_______________________________________________ 
 I am new to python application development but I greatly prefer your application over the other FOSS candidate I am working with"OpenEMR". Thank you.

**Comment by Kanr** [comment]
@dreaswar Thank you for the reply, I am only just now getting back to my experiementing with AuShada. I am slowly moving towards a working prototype but continue having configuration errors. Currently I am having trouble installing psycopg2 in my virtualenv. If you have any insights on how I can clear my error I would appreciate it.

**Comment by dreaswar** [comment]
@Kanr , What specific errors are you getting with psycopg2
